//
//  AugmentationView.swift
//  Neural Hacker
//
//  Created by João Pedro Picolo on 22/04/22.
//

import SwiftUI
import SpriteKit

struct AugmentationView: View {
    private let screenWidth = UIScreen.main.bounds.size.width
    private let screenHeight = UIScreen.main.bounds.size.height
    
    private var images: [AgumentationImage] = [
        AgumentationImage(name: "jair-face"),
        AgumentationImage(name: "jair-face"),
        AgumentationImage(name: "jair-face"),
        AgumentationImage(name: "jair-face"),
        AgumentationImage(name: "jair-face"),
        AgumentationImage(name: "jair-face"),
        AgumentationImage(name: "jair-face"),
        AgumentationImage(name: "jair-face"),
        AgumentationImage(name: "jair-face"),
        AgumentationImage(name: "jair-face"),
        AgumentationImage(name: "jair-face"),
        AgumentationImage(name: "jair-face"),
    ]
    
    @State private var options: [AugmentationType] = [
        AugmentationType(type: "Flipping"),
        AugmentationType(type: "Rotation"),
        AugmentationType(type: "Brightness")
    ]
    
    @StateObject private var scene: DeviceScene = {
        let screenWidth = UIScreen.main.bounds.size.width
        let screenHeight = UIScreen.main.bounds.size.height
        let scene = DeviceScene()
        
        scene.size = CGSize(width: screenWidth, height: screenHeight)
        scene.scaleMode = .fill
        scene.backgroundColor = .white
        return scene
    }()
    
    
    
    var body: some View {
        let imageWidth = scene.deviceNode.size.width
        let imageHeight = scene.deviceNode.size.height
        
        VStack {
            SpriteView(scene: scene)
                .frame(width: screenWidth, height: screenHeight)
                .ignoresSafeArea()
        }
        .overlay {
            VStack {
                HStack(alignment: .top, spacing: 10) {
                    Image("jair-multi")
                        .overlay(RoundedRectangle(cornerRadius: 2)
                            .stroke(.black, lineWidth: 1))
                        .shadow(radius: 1)
                    
                    Text("Select the methods you want to use in order to generate more images. You're gonna have a preview  of the images, and will be able to see how many images we've generated by the end.")
                        .padding(.top, 20)
                }
                .frame(
                    width: imageWidth - (imageWidth / 4) - 40,
                    height: 200,
                    alignment: .bottom
                )
                .padding(.top, 20)
                
                VStack(alignment: .center, spacing: 20) {
                    ForEach(0..<3) { i in
                        HStack {
                            Image(systemName: options[i].used ? "checkmark.square": "square")
                            Text(options[i].type)
                        }
                        .frame(
                            width: imageWidth - (imageWidth / 4) - 25,
                            height: 40,
                            alignment: .leading
                        )
                        
                        .padding(.bottom, -20)
                        .onTapGesture {
                            options[i].used = !options[i].used
                        }
                        
                        HStack(alignment: .center, spacing: 30) {
                            ForEach(0..<4) { j in
                                VStack {
                                    Image(images[(i * 3) + j].name)
                                        .resizable()
                                        .frame(width: 150, height: 150, alignment: .center)
                                }
                                .overlay(RoundedRectangle(cornerRadius: 2)
                                    .stroke(.black, lineWidth: 1))
                                .shadow(radius: 1)
                            }
                        }
                    }
                    
                    NavigationLink(destination: NetworkView()) {
                        VStack {
                            Text("Next")
                        }
                        .frame(width: screenWidth / 8, height: 20, alignment: .bottom)
                        .foregroundColor(.white)
                        .padding()
                        .background(.red)
                        .cornerRadius(10)
                        .padding(.top, 10)
                    }
                }
                .frame(
                    width: imageWidth - (imageWidth / 4) - 20,
                    height: imageHeight - (imageHeight / 20) - 240,
                    alignment: .center
                )
                
                Spacer()
            }
            .frame(
                width: imageWidth - (imageWidth / 4) - 20,
                height: imageHeight - (imageHeight / 20),
                alignment: .topLeading
            )
            
            
            
        }
        .navigationBarHidden(true)
    }
}

struct AgumentationImage {
    var name: String
}

struct AugmentationType {
    var type: String
    var used = false
}


